image: golang:1.18-alpine

stages:
  - release

create_tag:
  image: node:lts
  stage: release
  before_script:
    - npm install -g semantic-release @semantic-release/gitlab
  script:
    - semantic-release
  only:
    - main
